[particles]
e1 = {
    name = "John the Particle",
    type = "electron",
    pos = [12.3, 4.8],
    vel = [3.14, 69.420, 8.00]
}
p1 = {
    name = "Larry the Proton",
    type = "proton",
    pos = [12.9, 48.6],
    vel = [3.14, 69.420, 8.00]
}