#[environment.dimensions]
#x = 100
#y = 100
#z = 100

[[particles]]
name = "John the Particle"
type = "electron"
pos = [12.3, 4.8]

[[particles]]
name = "Larry the Proton"
type = "proton"
pos = [12.9, 48.6]

[[atoms]]

