[configuration]
width   = 1920
height  = 1080
rgb     = [0, 0, 0]

[[particles]]
type = "neutron"
pos = [-500, 300]
vel = [3.14, 69.420, 8.00]

[[particles]]
type = "proton"
pos = [274, 123]
vel = [3.14, 69.420, 8.00]

