[configuration]
width   = 1920
height  = 1080
rgb     = [0, 0, 0]
delay   = 100

[[particles]]
type = "neutron"
pos = [30, 30]
vel = [0, 0]

[[particles]]
type = "proton"
pos = [20, 50]
vel = [0, 0]

[[particles]]
type = "proton"
pos = [10, 10]
vel = [0, 0]

[[particles]]
type = "electron"
pos = [20, 15]
vel = [0, 0]

[[particles]]
type = "electron"
pos = [0, 0]
vel = [0, 0]